### ISSUE TITLE
ROADMAP for Project Rewrite

### ISSUE THREAD

**Issue by anhzf** [anhzf/evote#11]
- [x] Authentication
  - [x] Google
  - [x] Vote Token
- [ ] Authorization
  - [x] Privilege by feature/action
- [ ] Voting Event Settings
  - [ ] Session
    - [ ] Open/Close voting session
    - [ ] Reset voting session
  - [ ] Privilege and Roles management
- [x] Voting Event Vote Page
  - [x] List of candidates
  - [x] Generate Vote Token
  - [x] Vote function
- [ ] Voting Event Result
  - [x] Result data visualization (Pie Chart)
  - [ ] Realtime data update
- [ ] Voting Event Voter List
  - [x] List of voters
  - [x] Import from CSV
  - [ ] Manually add Voter
  - [x] Delete Voter

## Nice to have
- [ ] Voting Event Settings
  - [ ] General
    - [ ] Update banner image
    - [ ] Update social media
    - [ ] Change url/link
  - [ ] Candidate Management
    - [ ] Add candidate
    - [ ] Remove candidate
    - [ ] Edit candidate
  - [ ] Scheduled session
- [ ] Voting Event Landing Page
  - [ ] Show banner image
  - [ ] Show social media
